[project]
name = "aq-data-az-blob"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-storage-blob>=12.26.0",
    "dotenv>=0.9.9",
    "pandas>=3.0.5",
    "pyarrow>=21.0.0",
    "tqdm>=4.70.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.4",
]

[tool.uv]
package = true

[tool.setuptools.packages.find]
include = ["aqblob*", "scripts*"]

[project.scripts]
upload = "scripts.upload_files:main"
download = "scripts.download_blobs:main"
list = "scripts.list_blobs:main"

