import os
from dotenv import load_dotenv

load_dotenv()

LOG_DIRECTORY_PATH = os.getenv("AQ_AZ_BLOB_LOG_DIRECTORY_PATH")
SOURCE_DIR_PATH = os.getenv("AQ_AZ_SOURCE_FILE_DIRECTORY_PATH")
DOWNLOADED_DIR_PATH = os.getenv("AQ_AZ_DOWNLOADED_DIR_PATH")
STAGING_DIR_PATH = os.getenv("AQ_AZ_STAGING_DIRECTORY_PATH")
AZ_STORAGE_CONNECTION_STRING = os.getenv("AQ_AZ_STORAGE_CONNECTION_STRING")
AZ_STORAGE_CONTAINER_NAME = os.getenv("AQ_AZ_STORAGE_CONTAINER_NAME")
AQ_PLATFORM_NAME = os.getenv("AQ_AZ_PLATFORM_NAME")
FILE_SUFFIXES = os.getenv("AQ_AZ_FILE_SUFFIXES", ".csv,.parquet,.json,.txt").split(",")