import os
from dotenv import load_dotenv

load_dotenv()

AQ_PLATFORM_NAME = os.getenv("AQ_PLATFORM_NAME")
AZ_STORAGE_CONNECTION_STRING = os.getenv("AQ_AZ_STORAGE_CONNECTION_STRING")
AZ_STORAGE_CONTAINER_NAME = os.getenv("AQ_AZ_STORAGE_CONTAINER_NAME")
SOURCE_DIR_PATH = os.getenv("AQ_AZ_SOURCE_FILE_DIRECTORY_PATH")
STAGING_DIR_PATH = os.getenv("AQ_AZ_STAGING_DIRECTORY_PATH")
LOG_DIRECTORY_PATH = os.getenv("AQ_BLOB_LOG_DIRECTORY_PATH")
DOWNLOADED_DIR_PATH = os.getenv("AQ_AZ_DOWNLOADED_DIR_PATH")